theme: jekyll-theme-slate
title: [Martin Einar Jensen]
description: [Lista yfir forrit sem ég hef verið hannað. Annaðhvort með einhverjum eða aleinn.]
github:
  repository_url: https://github.com/mej3hi
